AllCops:
  Exclude:
    - vendor/**/*
    - bin/**/*
    - test/dummy/**/*

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

ClassLength:
  Enabled: false

Documentation:
  # don't require classes to be documented
  Enabled: false

Encoding:
  # no need to always specify encoding
  Enabled: false

NumericLiterals:
  Enabled: false

FileName:
  Enabled: false
